spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/studycoach
    username: studyuser
    password: studypass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  logging:
    level:
      org.hibernate.SQL: OFF
      org.hibernate.type.descriptor.sql.BasicBinder: OFF
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral
studycoach:
  topics:
    - arrays
    - hashmaps
    - sliding window
    - two pointers
    - stack
    - queue
    - binary search
    - sliding window
    - linked list
    - trees
    - tries
    - backtracking
    - heaps
    - priority queue
    - interval
    - greedy
    - dynamic programming
    - graphs
  trusted sources:
    - NeetCode
    - Gaurav Sen
    - Hello Interview

server:
  port: 8080